version: '3'
services:
    node:
        image: node:14.19.1-alpine
        working_dir: /app
        volumes:
            - '.:/app'

    serverless:
        build:
            context: .
            dockerfile: serverless.Dockerfile
            args:
                - NODE_ALPINE_IMAGE=node:14.19.1-alpine
                - SERVERLESS_VERSION=3.7.8
        working_dir: /app
        env_file: '.env'
        volumes:
            - '.:/app'
        entrypoint: /app/scripts/deploy.sh
