service: scraper-service

frameworkVersion: '3'

plugins:
    - serverless-webpack
    - serverless-iam-roles-per-function

provider:
    name: aws
    runtime: nodejs14.x
    timeout: 30
    stage: ${opt:stage, 'dev'}
    region: ap-southeast-2
    environment:
        WEB_SNAPSHOTS_BUCKET_NAME: ${self:custom.WebSnapshotsBucket.name}

layers:
    chromeAWSLambda:
        package:
            artifact: layers/chrome_aws_lambda.zip

resources:
    Resources:
        WebSnapshotsBucket: ${file(resources/WebSnapshotsBucket.yml):WebSnapshotsBucket}

functions:
    scrapeWeb:
        handler: src/handlers/scrapeWeb.handler
        layers:
            - { Ref: ChromeAWSLambdaLambdaLayer }
        events:
            - http:
                  method: POST
                  path: /scrape
        iamRoleStatements:
            - ${file(iam/WebSnapshotsBucketIAM.yml):WebSnapshotsBucketIAM}

custom:
    WebSnapshotsBucket:
        name: web-snapshots-bucket-sdy8id-${self:provider.stage}
